# Site settings
title: Crowetic computers
email: irontiga@gmail.com
description: "Crowetic's website"
baseurl: "/crowetic-site" # the subpath of your site, e.g. /blog/
url: "http://irontiga.github.com" # the base hostname & protocol for your site
twitter_username: 
github_username: irontiga

# Build settings
markdown: kramdown

#paginate: 4
#paginate_path: "/blog/page/:num/"

permalink: /blog/:title/

collections:
  docs:
    output: false #true
    permalink: /docs/:path/